services:
  redis:
    networks:
      - ckb-discovery
    image: 'bitnami/redis:latest'
    environment:
      - REDIS_PASSWORD=CkBdIsCoVeRy
    volumes:
      - ./data/redis:/bitnami/redis/data
    ports:
      - '6379:6379'
  mqtt:
    networks:
      - ckb-discovery
    image: "emqx/emqx"
    environment:
      - EMQX_ALLOW_ANONYMOUS=false
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "18083:18083"
  exposed:
    networks:
      - ckb-discovery
    environment:
      - REDIS_URL=redis://:CkBdIsCoVeRy@redis
    build:
      context: ./
      dockerfile: ./exposed/Dockerfile
    ports:
      - '1800:1800'
    depends_on:
      - redis
  marci:
    networks:
      - ckb-discovery
    environment:
      - REDIS_URL=redis://:CkBdIsCoVeRy@redis
      - MQTT_URL=mqtt://ckb:ckbdiscovery@mqtt:1883
    build:
      context: ./
      dockerfile: ./marci/Dockerfile
    depends_on:
      - mqtt
      - redis

networks:
  ckb-discovery:
    driver: bridge
