services:
  redis:
    networks:
      - ckb-discovery
    image: 'bitnami/redis:latest'
    environment:
      - REDIS_PASSWORD=CkBdIsCoVeRy
    volumes:
      - ./data/redis:/bitnami/redis/data
    ports:
      - '6379:6379'
  mqtt:
    networks:
      - ckb-discovery
    image: 'bytebeamio/rumqttd'
    ports:
      - '1883:1883'
      - '1884:1884'
  exposed:
    networks:
      - ckb-discovery
    environment:
      - REDIS_URL=redis://:CkBdIsCoVeRy@redis
    build:
      context: ./
      dockerfile: ./exposed/Dockerfile
    ports:
      - '1800:1800'
    depends_on:
      - redis
  marci:
    networks:
      - ckb-discovery
    environment:
      - REDIS_URL=redis://:CkBdIsCoVeRy@redis
      - MQTT_URL=mqtt://mqtt:1883
    build:
      context: ./
      dockerfile: ./marci/Dockerfile
    depends_on:
      - mqtt
      - redis

networks:
  ckb-discovery:
    driver: bridge
