services:
  redis:
    networks:
      - ckb-discovery
    image: 'bitnami/redis:latest'
    environment:
      - REDIS_PASSWORD=${REDIS_PASS}
    volumes:
      - ./data/redis:/bitnami/redis/data
    ports:
      - '6379:6379'
  mqtt:
    networks:
      - ckb-discovery
    image: "emqx/emqx"
    environment:
      - EMQX_ALLOW_ANONYMOUS=false
      - EMQX_DASHBOARD__DEFAULT_PASSWORD=${MQTT_ADMIN_PASS}
      - EMQX_AUTH__USER__1__USERNAME=${MQTT_USER}
      - EMQX_AUTH__USER__1__PASSWORD=${MQTT_PASS}
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "18083:18083"
  exposed:
    networks:
      - ckb-discovery
    environment:
      - REDIS_URL=redis://:${REDIS_PASS}@redis
    build:
      context: ./
      dockerfile: ./exposed/Dockerfile
    ports:
      - '1800:1800'
    depends_on:
      - redis
  marci:
    networks:
      - ckb-discovery
    environment:
      - REDIS_URL=redis://:${REDIS_PASS}@redis
      - MQTT_URL=mqtt://mqtt:1883
      - MQTT_USER=${MQTT_USER}
      - MQTT_PASS=${MQTT_PASS}
    build:
      context: ./
      dockerfile: ./marci/Dockerfile
    depends_on:
      - mqtt
      - redis

networks:
  ckb-discovery:
    driver: bridge
